### ISSUE TITLE
Can't modify the App.vue file - keeps rejecting the save

### ISSUE THREAD

**Issue by jimmack1963** [Akryum/meteor-vue2-example#1]
I am on Windows (sorry) and using Visual Studio code, so it's probably my lack of experience, but as soon as I change anything - even just text in the <p>, it goes into an infinite loop of trying to save the file, going possibly to some kind of compile rejection, and coming back unsaved in the VS gui.  

The console (chrome) reveals: 

>  vue.runtime.common.js:509 [Vue warn]: Failed to mount component: template or render function not defined. 
> (found in anonymous component - use the "name" option for better debugging messages.)warn @ vue.runtime.common.js:509Vue._mount @ vue.runtime.common.js:2324Vue$2.$mount @ vue.runtime.common.js:5916init @ vue.runtime.common.js:2646createComponent @ vue.runtime.common.js:4030createElm @ vue.runtime.common.js:3973patch @ vue.runtime.common.js:4448Vue._update @ vue.runtime.common.js:2366(anonymous function) @ vue.runtime.common.js:2333get @ vue.runtime.common.js:1639run @ vue.runtime.common.js:1708flushSchedulerQueue @ vue.runtime.common.js:1526(anonymous function) @ vue.runtime.common.js:461nextTickHandler @ vue.runtime.common.js:410(anonymous function) @ dynamics_browser.js:51
> 2dev-client.js:133 [HMR] Reloading imports/ui/App.vue

I've just upgraded to Meteor 1.4.2.3.
node 6.9.1

and the behavior is the same, but the errors have changed to

> modules.js?hash=f02f19a…:1190 [Vue warn]: Failed to mount component: template or render function not defined. 
> (found in anonymous component - use the "name" option for better debugging messages.)warn @ modules.js?hash=f02f19a…:1190Vue._mount @ modules.js?hash=f02f19a…:3005Vue$2.$mount @ modules.js?hash=f02f19a…:6597init @ modules.js?hash=f02f19a…:3327createComponent @ modules.js?hash=f02f19a…:4711createElm @ modules.js?hash=f02f19a…:4654patch @ modules.js?hash=f02f19a…:5129Vue._update @ modules.js?hash=f02f19a…:3047(anonymous function) @ modules.js?hash=f02f19a…:3014get @ modules.js?hash=f02f19a…:2320run @ modules.js?hash=f02f19a…:2389flushSchedulerQueue @ modules.js?hash=f02f19a…:2207(anonymous function) @ modules.js?hash=f02f19a…:1142nextTickHandler @ modules.js?hash=f02f19a…:1091(anonymous function) @ meteor.js?hash=e3f53db…:1105
> 2dev-client.js:133 [HMR] Reloading imports/ui/App.vue

**Comment by jimmack1963** [comment]
PS I have coffeescript package, and it is working on other code.

**Comment by jimmack1963** [comment]
Also, I can edit .vue file and see things with different editor, so it's a combination of visual studio code + addins.  Maybe not worth your time to look at, but am willing to help if you want to check anything out!

**Comment by Akryum** [comment]
I don't really use Visual Code and don't have time to look for editor specific issues, but thanks a lot for your report. Maybe you could investigate and gather information on how Visual Code saves the files.

**Comment by jimmack1963** [comment]
Sure, as I learn.  I'm new to it as well, having been a webstorm fan (still am, just looking around).  Thank you for all your great work on vue integration to meteor!
