### ISSUE TITLE
Anonymous Component in Vue dev tools

### ISSUE THREAD

**Issue by mitar** [Akryum/meteor-vue2-example#4]
In Vue dev tools, the app component is named "Anonymous Component". Is there some way to correctly name it?

**Comment by Akryum** [comment]
Add a `name` option to the component definition.

**Comment by mitar** [comment]
I thought that the name is automatically added for single file components?

**Comment by Akryum** [comment]
No it isn't. ^^

**Comment by mitar** [comment]
Any reason why this would not be done so? From what I see Vue tries `vm.$options.name || vm.$options._componentTag` in `warn` (not sure for dev tools). So `_componentTag` could be set?

**Comment by Akryum** [comment]
Well because you can set a different name that will be used for aromatic
registration. I usually name my components, even in non Meteor apps.

**Comment by mitar** [comment]
So, why wouldn't we name components the same as they are registered under using automatic registration, if user does not name them themselves?

**Comment by Akryum** [comment]
We could. 😄

**Comment by mitar** [comment]
I opened: https://github.com/Akryum/meteor-vue-component/issues/99
